export const FETCH_POST_PENDING = "FETCH_POST_PENDING";
export type FETCH_POST_PENDING = typeof FETCH_POST_PENDING;

export const FETCH_POST_FULLFILED = "FETCH_POST_FULLFILED";
export type FETCH_POST_FULLFILED = typeof FETCH_POST_FULLFILED;

export const FETCH_POST_REJECTED = "FETCH_POST_REJECTED";
export type FETCH_POST_REJECTED = typeof FETCH_POST_REJECTED;
