export const articleRelatedGuide = {
	Name: "Audio-related-guides",
	Title: "Audio section title",
	IntroText: "test\nintro line",
	SupportContent:
		'<p>Feeling stressed and anxious at work is common. This is referred to as \'<strong>work-related or occupational stress</strong>\'.</p><p>In the UK, more than half a million people report that work is making them stressed, anxious or depressed each year, with 12.5 million working days lost because of it.</p><p>Almost half of all working days lost (49 per cent) are due to stress, anxiety or depression.</p><p>If you’re suffering from work-related stress, you may feel you’re in a minority but hopefully these figures will show that you’re not alone.</p><p>However, just because it’s common doesn’t mean it’s acceptable or that you have to live with it.</p><h4>The definition of work-related stress</h4><p>According to the <a href="http://www.hse.gov.uk/stress/what-to-do.htm">Health &amp; Safety Executive</a>, work-related stress is \'a harmful reaction that people have to undue pressures and demands placed on them at work\', whether it’s physical or psychological.</p><h4>Work-related stress symptoms</h4><p>Work-related stress can lead to poor health (and, in some cases, injury), with common symptoms including:</p><ul class="bulleted"><li>Tiredness</li><li>Muscle tension</li><li>Headaches</li><li>Heart palpitations</li><li>Gastrointestinal problems, such as diarrhoea or constipation</li><li>Skin disorders (such as eczema)</li><li>Trouble sleeping</li><li>Tearfulness</li><li>Anxiety disorders</li><li>Depression</li><li>Physical illness</li></ul><h4>Causes of work-related stress</h4><p>Research shows there are a number of key ways in which work-related stress can affect us.</p><p>Some factors are brief or time-limited and others are ongoing and tend to be caused by either performance or relationship factors.</p><h4>Peformance factors</h4><ul class="bulleted"><li>Almost half (44 per cent) of all work-related stress incidents are due to workload related factors such as tight deadlines, too much work or too much pressure.</li><li>Organisational changes at work</li><li>Role uncertainty including lack of clarity about a job or uncertainty of what is expected</li><li>Lack of control such as the pressures of a long and/or difficult commute or working away from home</li><li>Our underlying beliefs and consequential behaviours</li></ul><h4>Relationship factors</h4><ul class="bulleted"><li>Violence, threats or bullying</li><li>Lack of managerial support</li></ul><p><img src="http://dborkovac.sitesstage.com/media/meppv22j/people.jpg?width=500&amp;height=194.44444444444443" alt="" width="500" height="194.44444444444443"></p><p><img src="http://dborkovac.sitesstage.com/media/tz0d0c35/mobile4.jpg?width=500&amp;height=452.7687296416938" alt="" width="500" height="452.7687296416938"></p><h4 class=\'divider\'>Divider module</h4>',
	SubSections: [
		{
			Name: "Reduce stress and anxiety",
			Title: "Reduce your symptoms",
			ModuleTitle: "Module Title",
			Touched: false,
			BackgroundImageUrl:
				"http://dborkovac.sitesstage.com/media/mzglyn1i/info2.jpg",
			IntroText: "Audio guides for managing work-related stress and anxiety",
			SupportContent:
				'<p>Feeling stressed and anxious at work is common. This is referred to as \'<strong>work-related or occupational stress</strong>\'.</p><p>In the UK, more than half a million people report that work is making them stressed, anxious or depressed each year, with 12.5 million working days lost because of it.</p><p>Almost half of all working days lost (49 per cent) are due to stress, anxiety or depression.</p><p>If you’re suffering from work-related stress, you may feel you’re in a minority but hopefully these figures will show that you’re not alone.</p><p>However, just because it’s common doesn’t mean it’s acceptable or that you have to live with it.</p><h4>The definition of work-related stress</h4><p>According to the <a href="http://www.hse.gov.uk/stress/what-to-do.htm">Health &amp; Safety Executive</a>, work-related stress is \'a harmful reaction that people have to undue pressures and demands placed on them at work\', whether it’s physical or psychological.</p><h4>Work-related stress symptoms</h4><p>Work-related stress can lead to poor health (and, in some cases, injury), with common symptoms including:</p><ul class="bulleted"><li>Tiredness</li><li>Muscle tension</li><li>Headaches</li><li>Heart palpitations</li><li>Gastrointestinal problems, such as diarrhoea or constipation</li><li>Skin disorders (such as eczema)</li><li>Trouble sleeping</li><li>Tearfulness</li><li>Anxiety disorders</li><li>Depression</li><li>Physical illness</li></ul><h4>Causes of work-related stress</h4><p>Research shows there are a number of key ways in which work-related stress can affect us.</p><p>Some factors are brief or time-limited and others are ongoing and tend to be caused by either performance or relationship factors.</p><h4>Peformance factors</h4><ul class="bulleted"><li>Almost half (44 per cent) of all work-related stress incidents are due to workload related factors such as tight deadlines, too much work or too much pressure.</li><li>Organisational changes at work</li><li>Role uncertainty including lack of clarity about a job or uncertainty of what is expected</li><li>Lack of control such as the pressures of a long and/or difficult commute or working away from home</li><li>Our underlying beliefs and consequential behaviours</li></ul><h4>Relationship factors</h4><ul class="bulleted"><li>Violence, threats or bullying</li><li>Lack of managerial support</li></ul><p><img src="http://dborkovac.sitesstage.com/media/meppv22j/people.jpg?width=500&amp;height=194.44444444444443" alt="" width="500" height="194.44444444444443"></p><p><img src="http://dborkovac.sitesstage.com/media/tz0d0c35/mobile4.jpg?width=500&amp;height=452.7687296416938" alt="" width="500" height="452.7687296416938"></p><blockquote>In this section of the app, we will consider useful approaches in helping you to manage your work-related stress and anxiety.</blockquote><h4 class=\'divider\'>Divide title </h4>',
			HasGroups: false,
			Items: [
				{
					Name: "Guided Rebreathing",
					FileId: 0,
					FilePath: null,
					FileExt: null,
					FileSize: 0,
					Description: "",
					Version: null,
					Voiceover: "",
					Backing: "",
					ContentFree: true,
				},
				{
					Name: "Mindfulness Body Scan",
					FileId: 1422,
					FilePath:
						"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
					FileExt: ".mp3",
					FileSize: 15627625,
					Description: "",
					Version: "",
					Voiceover: "",
					Backing: "",
					ContentFree: false,
				},
				{
					Name: "Safe Space",
					FileId: 1422,
					FilePath:
						"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
					FileExt: ".mp3",
					FileSize: 15627625,
					Description: "",
					Version: "",
					Voiceover: "",
					Backing: "",
					ContentFree: false,
				},
			],
			ContentFree: true,
		},
		{
			Name: "Improve your thinking and mental resilience",
			Title: "Improve mental health",
			ModuleTitle: "improve",
			Touched: true,
			BackgroundImageUrl:
				"http://dborkovac.sitesstage.com/media/mzglyn1i/info2.jpg",
			IntroText: "",
			SupportContent: "",
			HasGroups: true,
			Items: [
				{
					Name: "Setting a goal for the day",
					Title: "Set a goal",
					Description: "Take a few moments to plan your goal for today",
					IntroText: "",
					Items: [
						{
							Name: "Setting a goal for the day - Morning - Male with backing",
							FileId: 1524,
							FilePath:
								"http://dborkovac.sitesstage.com/media/s5ijubiu/breathing-morning_pre-edit.mp3",
							FileExt: ".mp3",
							FileSize: 12410880,
							Description: "",
							Version: "Morning",
							Voiceover: "Male",
							Backing: "With",
							ContentFree: true,
						},
						{
							Name: "Setting a goal for the day - Morning - Female with backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "Female track",
							Version: "Morning",
							Voiceover: "Female",
							Backing: "With",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Morning - Male without backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Morning",
							Voiceover: "Male",
							Backing: "Without",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Morning - Female without backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "Female track",
							Version: "Morning",
							Voiceover: "Female",
							Backing: "Without",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Afternoon - Male with backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Afternoon",
							Voiceover: "Male",
							Backing: "With",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Afternoon -Female with backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "Female track",
							Version: "Afternoon",
							Voiceover: "Female",
							Backing: "With",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Afternoon - Male without backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Afternoon",
							Voiceover: "Male",
							Backing: "Without",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Afternoon -Female without backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "Female track",
							Version: "Afternoon",
							Voiceover: "Female",
							Backing: "Without",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Evening Male with backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Evening",
							Voiceover: "Male",
							Backing: "With",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Evening Female with backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Evening",
							Voiceover: "Female",
							Backing: "With",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Evening Male without backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Evening",
							Voiceover: "Male",
							Backing: "Without",
							ContentFree: false,
						},
						{
							Name: "Setting a goal for the day - Evening Female without backing",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Evening",
							Voiceover: "Female",
							Backing: "Without",
							ContentFree: false,
						},
					],
					ContentFree: true,
				},
				{
					Name: "Stress bucket",
					Title: "",
					Description: "Learn how to use your imaginary stress bucket",
					IntroText: "",
					Items: [
						{
							Name: "Stress bucket - morning",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "Stress bucket - morning desciption",
							Version: "Morning",
							Voiceover: "",
							Backing: "",
							ContentFree: false,
						},
						{
							Name: "Stress bucket - Afternoon",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "Stress bucket - Afternoon description",
							Version: "Afternoon",
							Voiceover: "",
							Backing: "",
							ContentFree: false,
						},
						{
							Name: "Stress bucket - Evening",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "Stress bucket - Evening description",
							Version: "Evening",
							Voiceover: "",
							Backing: "",
							ContentFree: false,
						},
					],
					ContentFree: false,
				},
				{
					Name: "Mindfulness and personal responsibility",
					Title: "",
					Description: "",
					IntroText: "",
					Items: [
						{
							Name: "Mindfulness and personal responsibility - Morning",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Morning",
							Voiceover: "",
							Backing: "",
							ContentFree: false,
						},
						{
							Name: "Mindfulness and personal responsibility - Afternoon",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "Afternoon",
							Voiceover: "",
							Backing: "",
							ContentFree: false,
						},
						{
							Name: "Mindfulness and personal responsibility - Evening",
							FileId: 1422,
							FilePath:
								"http://dborkovac.sitesstage.com/media/kcsgvd3l/positive_guided_imagery.mp3",
							FileExt: ".mp3",
							FileSize: 15627625,
							Description: "",
							Version: "",
							Voiceover: "",
							Backing: "",
							ContentFree: false,
						},
					],
					ContentFree: false,
				},
			],
			ContentFree: true,
		},
	],
	ContentFree: true,
};
